version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: trr-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      tr2g2-back:
        condition: service_started
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  tr2g2-back:
    image: node:23-bookworm-slim
    command: sh -c "cp -f .env.PROD .env && npm install && node index.js"
    volumes:
      - ./back:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 8000:8000

  tr2g2-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: GESTIO-CURSOS
    volumes:
      - mysql-db:/var/lib/mysql:rw
      # - ./back/data/create_db.sql:/docker-entrypoint-initdb.d/create.sql
      # - ./back/data/insert_db.sql:/docker-entrypoint-initdb.d/inserts.sql

  tr2g2-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: tr2g2-mysql
    depends_on:
      - tr2g2-mysql

  tr2g2-portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443

volumes:
  mysql-db:
  portainer_data:
