# Per iniciar l'entorn de desenvolupament, executeu:
# docker compose -f docker-compose.dev.yml up --build

# Per executar les migracions de la base de dades:
# docker compose -f docker-compose.dev.yml exec tr2g2-back npx prisma migrate dev

# Per executar la inicialització de la base de dades:
# docker compose -f docker-compose.dev.yml exec tr2g2-back npx prisma db seed

services:
  tr2g2-front:
    image: node:23-bookworm-slim
    command: sh -c "cp .env.DEV .env && npm install && npm run dev"
    volumes:
      - ./front:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    links:
      - tr2g2-back
    environment:
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
  tr2g2-back:
    build:
      dockerfile: ./back/dev.Dockerfile
      context: .
    command: sh -c "rm -rf ./generated/prisma && cp .env.DEV .env && npm install && npx prisma generate && npm run dev"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules # SOLUCIÓN 1: Evita conflictos de archivos en Windows
    working_dir: /usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - tr2g2-mysql
    environment:
      # SOLUCIÓN 2: Conexión directa para que Prisma la detecte sin depender del .env
      DATABASE_URL: "mysql://root:root@tr2g2-mysql:3306/GESTIO-CURSOS"

  tr2g2-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GESTIO-CURSOS
    volumes:
      - mysql-db:/var/lib/mysql:rw
      # - ./back/data/create_db.sql:/docker-entrypoint-initdb.d/create.sql
      # - ./back/data/insert_db.sql:/docker-entrypoint-initdb.d/inserts.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: tr2g2-mysql
    depends_on:
      - tr2g2-mysql

volumes:
  mysql-db:
